[package]
name = "neteye"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
pnet = "0.35.0"
mac_oui = { version = "0.4.11", features = ["with-db"] }
clap = { version = "4.5.53", features = ["derive"] }
slint = "1.14.1"

[build-dependencies]
slint-build = "1.14"