[package]
name = "scan-core"
version = "0.1.0"
edition = "2024"

[dependencies]
pnet = "0.35.0"
mac_oui = { version = "0.4.11", features = ["with-db"] }

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[features]
default = []
serialize = ["serde"]
deserialize = ["serde"]